### ISSUE TITLE
missing screenshot for feature_accel_discs

### ISSUE THREAD

**Issue by wzhd** [pebble/pebble-sdk-examples#17]
There is an broken image at [this page](https://github.com/pebble/pebble-sdk-examples/tree/master/watchapps/feature_accel_discs).

The file `pebble-sdk-examples/watchapps/feature_accel_discs/README.md` contains this line

> !\[screenshot\](feature_accel_discs_screenshot.png)

But there is no such file.

**Comment by C-D-Lewis** [comment]
#18 will fix this.
